#!/bin/sh
uci set wireless.@wifi-device[0].disabled='0'
uci set wireless.@wifi-iface[0].ssid='OpenWRT'
uci set wireless.@wifi-iface[0].encryption='psk2'
uci set wireless.@wifi-iface[0].key='Passw0rd'
uci set wireless.@wifi-iface[0].network='lan'
uci commit wireless
exit 0
